services:
  - type: web
    name: my-flask-app
    repo: https://github.com/David11253/-my-first-project   # Укажите ваш репозиторий
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
