services:
- type: web
  name: my-first-project
  runtime: python
  repo: https://github.com/David11253/my-first-project
  plan: free
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -b 0.0.0.0:5000 server:app
version: "1"
